spring.application.name=web

server.servlet.context-path=/zal    

# 포트 번호
server.port=8095


# 데이터 베이스 연결
spring.datasource.url=jdbc:oracle:thin:@project-db-campus.smhrd.com:1523:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=park
spring.datasource.password=smhrd2

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 2. (선택사항) 알아서 구현된 sql console 에 출력
spring.jpa.show-sql=true
# 3. (선택사항) sql console 에서 실행되는 sql 문법을 예쁘게 출력
spring.jpa.properties.hibernate.format_sql=true

# 4. (필요에 따라 변경) DDL 자동 생성
# create-drop : 서버가 시작될 때 테이블을 생성하고, 서버가 종료될 때 테이블을 삭제
# update : 서버가 시작될 때 테이블을 생성하고, 기존 테이블은 유지
# validate : 서버가 시작될 때 테이블이 존재하는지 확인하고, 없으면 에러 발생
# none : DDL 자동 생성 안함
spring.jpa.hibernate.ddl-auto=update